### ISSUE TITLE
JaBbA installation error

### ISSUE THREAD

**Issue by mandronescu** [mskilab-org/JaBbA#94]
Hello, I am trying to install JaBbA with Gurobi in R 4.3.1 (under Rstudio 2023.09), on a MacOS 13.6 (64-bit). I successfully installed Gurobi and ran an example in R. When I try to install JaBbA using `devtools::install_github('mskilab/JaBbA')`, I get the following error:

Warning: multiple methods tables found for ‘%&%’
JaBbA 2023-10-06 12:15:20.954732: ${CPLEX_DIR}/cplex not found
Error: package or namespace load failed for ‘JaBbA’:
 .onLoad failed in loadNamespace() for 'JaBbA', details:
  call: fun(libname, pkgname)
  error: object 'testOptimizationFunction' not found
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/JaBbA’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/_1/p32n59195519xglhbr23ch800000gn/T//RtmpSqVlsl/file1683d5bae49/JaBbA_1.1.tar.gz’ had non-zero exit status

Your advice will be very appreciated. Thank you!

**Comment by shihabdider** [comment]
This is because we recently added a new method `testOptimizationFunction` to one of the dependency packages (`gGnome`). This change has just been merged. Please try `devtools::install_github('mskilab-org/gGnome')` to pull the latest version of gGnome and then try reinstalling JaBbA.

**Comment by mandronescu** [comment]
Thank you! I installed gGnome, but now I get another error. Note that I am trying to use JaBbA with Gurobi, not CPLEX.

JaBbA 2023-10-06 14:26:32.096997: ${CPLEX_DIR}/cplex not found
CPLEX is not wired with gGnome, Make sure CPLEXDIR exists in your .bashrc to add CPLEX functionality in gGnome.
Error: package or namespace load failed for ‘JaBbA’:
 .onLoad failed in loadNamespace() for 'JaBbA', details:
  call: value[[3L]](cond)
  error: ${CPLEX_DIR}/cplex not found
Error: loading failed
Execution halted

**Comment by shihabdider** [comment]
We have just merged a PR that should address this error. JaBbA should now have an exception for gurobi. Please try reinstalling JaBbA.

**Comment by mandronescu** [comment]
Thank you, but I still get a very similar error. Please advise, thank you!

JaBbA 2023-10-10 14:00:37.77823: ${CPLEX_DIR}/cplex not found
CPLEX is not wired with gGnome, Make sure CPLEXDIR exists in your .bashrc to add CPLEX functionality in gGnome.
Error: package or namespace load failed for ‘JaBbA’:
 .onLoad failed in loadNamespace() for 'JaBbA', details:
  call: value[[3L]](cond)
  error: ${CPLEX_DIR}/cplex not found
Error: loading failed
Execution halted

**Comment by shihabdider** [comment]
We have just merged another PR that should address this issue. Please reinstall JaBbA and try again and let us know if you're still encountering problems.

**Comment by mandronescu** [comment]
Thank you, that worked to install JaBbA with Gurobi! However, I am now trying to run it on the simple example provided and I'm running into some problems. 

1) The first time I run it with `jba ${JABBA_PATH}/junctions.vcf ${JABBA_PATH}/coverage.txt --gurobi TRUE`, it doesn't find the segmentation, so it runs segmentation, it saves the seg.rds file, but then it gives an error:

" .....
JaBbA 2023-10-16 16:29:56.631185: No segmentation provided, so performing segmentation using CBS
JaBbA 2023-10-16 16:29:56.694123: Segmentation finished
.....
JaBbA 2023-10-16 16:29:58.848608: Built gGraph with 82 nodes, 104 edges, purity 0.6, and ploidy 1.93
Error in !is.null(formatting(object)$y.field) && !is.na(formatting(object)$y.field) : 
  'length = 2' in coercion to 'logical(1)'
Calls: suppressPackageStartupMessages ... validObject -> anyStrings -> isTRUE -> validityMethod
"

2) Then, if I run it the second time, since it has the segmentation file it uses it, it seems to work fine, it creates the jaba.simple.gg.rds file, but then it gives some plotting errors:

" ...
Generating figures
JaBbA 2023-10-16 16:46:15.355457: Something wrong with plotting JaBbA results. Please try it later.
JaBbA 2023-10-16 16:46:15.382705: Something wrong with plotting JaBbA simplified results. Please try it later.
..."

Thank you for your help!

**Comment by shihabdider** [comment]
Unfortunately, I was unable to reproduce this error. However, it seems like this an issue with [gTrack](https://github.com/mskilab-org/gTrack), not JaBbA itself. gTrack is another package developed by our lab which here is used to visualize JaBbA outputs. I've gone ahead and opened a new issue for you [here](https://github.com/mskilab-org/gTrack/issues/32). I'm going to close this issue as completed since you were able to successfully install JaBbA, but I'll be happy to assist you in the new issue thread.
